version: '3.3'
services:
  web:
    build: .
    container_name: php65
    depends_on:
      - db
    ports:
      - 8008:80
  db:
    container_name: mysql8
    image: mysql_todo:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Todo
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
       - 6033:3306
